# Generated by Django 3.0 on 2020-05-25 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
                ('category', models.ForeignKey(default='category', on_delete=django.db.models.deletion.CASCADE, to='imageapp.Category')),
                ('location', models.ForeignKey(default='location', on_delete=django.db.models.deletion.CASCADE, to='imageapp.Location')),
            ],
        ),
    ]
