# Generated by Django 3.0 on 2020-05-24 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='category',
            field=models.ForeignKey(default='category', on_delete=django.db.models.deletion.CASCADE, to='gallery_images.Category'),
        ),
        migrations.AddField(
            model_name='images',
            name='location',
            field=models.ForeignKey(default='location', on_delete=django.db.models.deletion.CASCADE, to='gallery_images.Location'),
        ),
    ]
