# Generated by Django 3.0 on 2020-05-24 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_images', '0002_auto_20200525_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='category',
            field=models.ForeignKey(default='id', on_delete=django.db.models.deletion.CASCADE, to='gallery_images.Category'),
        ),
        migrations.AlterField(
            model_name='images',
            name='location',
            field=models.ForeignKey(default='id', on_delete=django.db.models.deletion.CASCADE, to='gallery_images.Location'),
        ),
    ]
