# Generated by Django 3.0 on 2020-05-25 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_images', '0006_auto_20200525_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Recent', 'Recent'), ('Family', 'Family'), ('Friends', 'Friends'), ('Travel', 'Travel'), ('Food', 'Food'), ('Fashion', 'Fashion'), ('Sports', 'Sports')], default='Recent', max_length=30),
        ),
        migrations.AlterField(
            model_name='images',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery_images.Category'),
        ),
        migrations.AlterField(
            model_name='images',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery_images.Location'),
        ),
    ]
