# Generated by Django 3.0 on 2020-05-25 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_images', '0007_auto_20200525_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='category',
        ),
    ]
